server:
  port: 4001

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
  info:
    title: "AI搜索"
    description: "AI智能搜索"
    version: "1.0"

mybatis-plus:
  type-aliases-package: com.ai.entity  # 实体类包路径
  mapper-locations: classpath*:/mapper/**/*.xml  # XML 文件路径
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 打印 SQL 日志
    map-underscore-to-camel-case: true  # 开启驼峰映射
  global-config:
    db-config:
      id-type: assign_id  # 主键生成策略（雪花算法）


spring:
  servlet:
    multipart:
      max-file-size: 10MB # 单个文件最大大小
      max-request-size: 50MB # 请求的最大大小
      upload-dir: G:/static/ai/
  application:
    name: player-ai
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: deepseek-r1:7b
  token:
    secret: ${SECRET} #token秘钥
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/play?characterEncoding=utf-8
    username: root
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    org.springframework.ai.chat.client.advisor: debug
    com.ai: debug