server:
  port: 4001

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
  info:
    title: "AI搜索"
    description: "AI智能搜索"
    version: "1.0"

mybatis-plus:
  type-aliases-package: com.ai.entity  # 实体类包路径
  mapper-locations: classpath*:/mapper/**/*.xml  # XML 文件路径
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 打印 SQL 日志
    map-underscore-to-camel-case: true  # 开启驼峰映射
  global-config:
    db-config:
      id-type: assign_id  # 主键生成策略（雪花算法）


spring:
  servlet:
    multipart:
      max-file-size: 10MB # 单个文件最大大小
      max-request-size: 50MB # 请求的最大大小
      location: G:/static/ai/
  application:
    name: ai
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: deepseek-r1:7b
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/play?characterEncoding=utf-8
    username: root
    password: wwq_2021
    driverClassName: com.mysql.cj.jdbc.Driver
    initialSize: 5  #初始建立连接数量
    minIdle: 5  #最小连接数量
    maxActive: 20 #最大连接数量
    maxWait: 10000  #获取连接最大等待时间，毫秒
    testOnBorrow: true #申请连接时检测连接是否有效
    testOnReturn: false #归还连接时检测连接是否有效
    timeBetweenEvictionRunsMillis: 60000 #配置间隔检测连接是否有效的时间（单位是毫秒）
    minEvictableIdleTimeMillis: 300000  #连接在连接池的最小生存时间（毫秒）

logging:
  level:
    org.springframework.ai.chat.client.advisor: debug
    com.ai: debug